import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  cardIssuer,
  gstinCheckChar,
  isAadhaarValid,
  isCardValid,
  isDrivingLicenceValid,
  isEmailValid,
  isGstinValid,
  isIfscValid,
  isIndianMobileValid,
  isKnownIfscBank,
  isLuhnValid,
  isPanValid,
  isPassportValid,
  isPincodeValid,
  isPlausibleBirthDate,
  isUpiHandleValid,
  isVerhoeffValid,
  parseDate,
  verhoeffCheckDigit,
} from './validators';

interface Fixture {
  valid: Array<{ cls: string; text: string; needsContext?: boolean }>;
  negatives: Array<{ text: string; why: string }>;
}

/**
 * Generated by scripts/make-pii-fixture.py, whose checksums are an independent
 * implementation. If the tables in validators.ts are wrong, these fail -- which is the
 * whole point of not generating the fixture from the code under test.
 */
const fixture = JSON.parse(
  readFileSync(join(process.cwd(), 'eval', 'corpus', 'identifiers.json'), 'utf8'),
) as Fixture;

function validOfClass(cls: string): string[] {
  return fixture.valid.filter((v) => v.cls === cls).map((v) => v.text);
}

describe('Verhoeff', () => {
  it('accepts every Aadhaar the generator produced', () => {
    const aadhaars = validOfClass('AADHAAR');
    expect(aadhaars.length).toBeGreaterThanOrEqual(8);
    for (const a of aadhaars) expect(isAadhaarValid(a)).toBe(true);
  });

  it('catches a single wrong digit', () => {
    // The property UIDAI chose Verhoeff for. A plain mod-10 sum would miss some of these.
    const [first] = validOfClass('AADHAAR');
    const digits = (first ?? '').replace(/\s/g, '');
    for (let i = 0; i < digits.length; i += 1) {
      const wrong = String((Number(digits[i]) + 1) % 10);
      const broken = digits.slice(0, i) + wrong + digits.slice(i + 1);
      expect(isVerhoeffValid(broken)).toBe(false);
    }
  });

  it('catches an adjacent transposition', () => {
    // The other property: the mistake a human makes copying from a card.
    const [first] = validOfClass('AADHAAR');
    const digits = (first ?? '').replace(/\s/g, '');
    let checked = 0;
    for (let i = 0; i < digits.length - 1; i += 1) {
      if (digits[i] === digits[i + 1]) continue;
      const swapped = digits.slice(0, i) + digits[i + 1] + digits[i] + digits.slice(i + 2);
      expect(isVerhoeffValid(swapped)).toBe(false);
      checked += 1;
    }
    expect(checked).toBeGreaterThan(5);
  });

  it('computes the check digit that makes a payload valid', () => {
    const payload = '23456789012';
    expect(isVerhoeffValid(payload + String(verhoeffCheckDigit(payload)))).toBe(true);
  });

  it('rejects numbers UIDAI does not issue', () => {
    expect(isAadhaarValid('0000 0000 0000')).toBe(false);
    expect(isAadhaarValid('1234 5678 9012')).toBe(false);
    expect(isAadhaarValid('234567890')).toBe(false); // too short
  });

  it('rejects anything that is not digits', () => {
    expect(isVerhoeffValid('12a4')).toBe(false);
    expect(isVerhoeffValid('')).toBe(false);
  });
});

describe('Luhn and card issuers', () => {
  it('accepts every card the generator produced', () => {
    for (const card of validOfClass('CARD')) {
      expect(isLuhnValid(card)).toBe(true);
      expect(isCardValid(card)).toBe(true);
      expect(cardIssuer(card)).not.toBeNull();
    }
  });

  it('rejects a valid-looking number that fails the checksum', () => {
    expect(isCardValid('4111111111111112')).toBe(false);
  });

  it('rejects a Luhn-valid number with no issuer prefix', () => {
    // Luhn alone accepts one string in ten. The prefix is what makes it a card.
    const digits = '9999999999999995';
    expect(isLuhnValid(digits)).toBe(true);
    expect(isCardValid(digits)).toBe(false);
  });

  it('knows RuPay, which an Indian deployment will actually see', () => {
    expect(cardIssuer('6521000000000008')).toBe('rupay');
  });

  it('tolerates the separators people type', () => {
    const [card] = validOfClass('CARD');
    const spaced = (card ?? '').replace(/(\d{4})(?=\d)/g, '$1 ');
    expect(isCardValid(spaced)).toBe(true);
  });
});

describe('PAN', () => {
  it('accepts every PAN the generator produced', () => {
    for (const pan of validOfClass('PAN')) expect(isPanValid(pan)).toBe(true);
  });

  it('rejects a fourth character that is not an entity type', () => {
    // D is not in ABCFGHLJPTKE. A *is* -- Association of Persons -- which is why
    // 'AAAAA0000Z' is a perfectly well-formed PAN and not a useful negative.
    expect(isPanValid('AAADA0000Z')).toBe(false);
    expect(isPanValid('AAAAA0000Z')).toBe(true);
  });

  it('rejects the wrong shape', () => {
    expect(isPanValid('ABCDE1234')).toBe(false);
    expect(isPanValid('ABCDE12345')).toBe(false);
    expect(isPanValid('ABCD01234F')).toBe(false);
  });
});

describe('GSTIN', () => {
  it('accepts every GSTIN the generator produced', () => {
    for (const g of validOfClass('GSTIN')) expect(isGstinValid(g)).toBe(true);
  });

  it('rejects a wrong check character', () => {
    const [gstin] = validOfClass('GSTIN');
    const first14 = (gstin ?? '').slice(0, 14);
    const right = gstinCheckChar(first14);
    const wrong = right === 'Z' ? 'Y' : 'Z';
    expect(isGstinValid(first14 + wrong)).toBe(false);
  });

  it('rejects an impossible state code', () => {
    const [gstin] = validOfClass('GSTIN');
    expect(isGstinValid(`50${(gstin ?? '').slice(2)}`)).toBe(false);
  });

  it('rejects a GSTIN whose embedded PAN is malformed', () => {
    expect(isGstinValid('29AAAAA0000Z1Z5')).toBe(false);
  });
});

describe('IFSC', () => {
  it('accepts every IFSC the generator produced, and knows the bank', () => {
    for (const ifsc of validOfClass('IFSC')) {
      expect(isIfscValid(ifsc)).toBe(true);
      expect(isKnownIfscBank(ifsc)).toBe(true);
    }
  });

  it('requires the zero in the fifth position', () => {
    expect(isIfscValid('HDFC1234567')).toBe(false);
  });

  it('accepts an unknown bank as a shape, but does not vouch for it', () => {
    expect(isIfscValid('ZZZZ0123456')).toBe(true);
    expect(isKnownIfscBank('ZZZZ0123456')).toBe(false);
  });
});

describe('UPI', () => {
  it('accepts every VPA the generator produced', () => {
    for (const vpa of validOfClass('UPI')) expect(isUpiHandleValid(vpa)).toBe(true);
  });

  it('rejects an email address, which has the same shape', () => {
    // Without the PSP list every address on the page becomes a VPA.
    expect(isUpiHandleValid('name@company.com')).toBe(false);
    expect(isUpiHandleValid('user@localhost')).toBe(false);
  });
});

describe('Indian mobile numbers', () => {
  it('accepts every number the generator produced', () => {
    for (const phone of validOfClass('PHONE')) expect(isIndianMobileValid(phone)).toBe(true);
  });

  it('requires a mobile series', () => {
    expect(isIndianMobileValid('1234567890')).toBe(false);
    expect(isIndianMobileValid('5555555555')).toBe(false);
  });

  it('handles the prefixes people type', () => {
    expect(isIndianMobileValid('+919845012345')).toBe(true);
    expect(isIndianMobileValid('09845012345')).toBe(true);
    expect(isIndianMobileValid('98450 12345')).toBe(true);
  });
});

describe('the rest', () => {
  it('validates emails', () => {
    for (const email of validOfClass('EMAIL')) expect(isEmailValid(email)).toBe(true);
    expect(isEmailValid('not-an-email')).toBe(false);
    expect(isEmailValid('a@b')).toBe(false);
  });

  it('validates passports', () => {
    for (const p of validOfClass('PASSPORT')) expect(isPassportValid(p)).toBe(true);
    expect(isPassportValid('Q1234567')).toBe(false); // Q is not issued
    expect(isPassportValid('K0234567')).toBe(false); // second char must be 1-9
  });

  it('validates driving licences', () => {
    for (const l of validOfClass('LICENCE')) expect(isDrivingLicenceValid(l)).toBe(true);
    expect(isDrivingLicenceValid('KA0118991234567')).toBe(false); // year too early
  });

  it('validates pincodes', () => {
    expect(isPincodeValid('560038')).toBe(true);
    expect(isPincodeValid('000000')).toBe(false);
    expect(isPincodeValid('999999')).toBe(false);
    expect(isPincodeValid('111111')).toBe(false);
  });

  it('parses the date formats Indian forms use', () => {
    expect(parseDate('17/04/1999')).toEqual({ year: 1999, month: 4, day: 17 });
    expect(parseDate('1999-04-17')).toEqual({ year: 1999, month: 4, day: 17 });
    expect(parseDate('17-04-1999')).toEqual({ year: 1999, month: 4, day: 17 });
    expect(parseDate('not a date')).toBeNull();
  });

  it('tells a birthday from a date', () => {
    const now = new Date('2026-08-27T00:00:00Z');
    expect(isPlausibleBirthDate('17/04/1999', now)).toBe(true);
    expect(isPlausibleBirthDate('31/12/2030', now)).toBe(false); // future
    expect(isPlausibleBirthDate('17/04/1850', now)).toBe(false); // nobody is 176
    expect(isPlausibleBirthDate('31/02/1999', now)).toBe(false); // not a real date
  });
});
