/**
 * Generates the server's JSON Schemas from extension/src/shared/contract.ts.
 *
 *   node scripts/gen-schema.mjs           write the files
 *   node scripts/gen-schema.mjs --check   fail if the committed files are stale
 *
 * `npm run build` regenerates before bundling and `npm test` runs the check, so the
 * Zod schemas and server/schema.json cannot drift apart without something going red.
 *
 * schema.json         the planner *response*, used for guided decoding. io:'input',
 *                     so fields carrying a default are optional -- the model may omit
 *                     them and the device fills them in.
 * schema.request.json the step *request*, used server-side for validation. io:'output',
 *                     because the device always sends a parsed object with defaults
 *                     already applied.
 */

import { build } from 'esbuild';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const contract = join(root, 'extension', 'src', 'shared', 'contract.ts');
const tmpDir = join(root, 'node_modules', '.cache', 'sih');
const tmpFile = join(tmpDir, 'contract.mjs');

const TARGETS = [
  { file: join(root, 'server', 'schema.json'), exportName: 'StepResponseSchema', io: 'input' },
  {
    file: join(root, 'server', 'schema.request.json'),
    exportName: 'StepRequestSchema',
    io: 'output',
  },
];

async function loadContract() {
  await mkdir(tmpDir, { recursive: true });
  await build({
    entryPoints: [contract],
    outfile: tmpFile,
    bundle: true,
    format: 'esm',
    platform: 'node',
    packages: 'external',
    logLevel: 'warning',
  });
  // Cache-bust so repeated runs in one process pick up edits.
  return import(`${pathToFileURL(tmpFile).href}?t=${Date.now()}`);
}

function render(mod, { exportName, io }) {
  const schema = mod[exportName];
  if (!schema) throw new Error(`contract.ts does not export ${exportName}`);
  const json = zodModule.toJSONSchema(schema, { target: 'draft-2020-12', io });
  return `${JSON.stringify(
    {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      title: exportName.replace(/Schema$/, ''),
      $comment:
        'GENERATED by scripts/gen-schema.mjs from extension/src/shared/contract.ts. Do not edit.',
      ...json,
    },
    null,
    2,
  )}\n`;
}

let zodModule;

async function main() {
  const check = process.argv.includes('--check');
  zodModule = await import('zod');
  const mod = await loadContract();

  let stale = false;
  for (const target of TARGETS) {
    const next = render(mod, target);
    const current = existsSync(target.file) ? await readFile(target.file, 'utf8') : null;
    if (current === next) continue;

    if (check) {
      stale = true;
      console.error(
        `schema drift: ${target.file.replace(root, '.')} does not match contract.ts. ` +
          `Run "npm run schema:gen" and commit the result.`,
      );
      continue;
    }
    await mkdir(dirname(target.file), { recursive: true });
    await writeFile(target.file, next, 'utf8');
    console.log(`wrote ${target.file.replace(root, '.')}`);
  }

  await rm(tmpFile, { force: true });
  if (stale) process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
