#!/usr/bin/env python3
"""Generate eval/corpus/identifiers.json -- the L1 precision/recall fixture.

Written in Python, deliberately, with its own implementations of Verhoeff, Luhn and the
GSTIN checksum. The TypeScript validators are tested against *these* numbers, so a
mistake in the TS tables produces a failing test rather than a fixture that agrees with
it. A fixture generated by the code under test proves only that the code agrees with
itself.

The negatives are the interesting half. Anything can pass a regex; the question is
whether a twelve-digit invoice number, a rupee amount with the separators stripped, or
an order id shaped exactly like an Aadhaar gets through. Roughly one random 12-digit
string in ten passes Verhoeff by chance, so the negatives include deliberately
Verhoeff-valid numbers sitting behind an "Invoice no." label -- those must be rejected
on context, not on arithmetic.

Run: python scripts/make-pii-fixture.py
"""

from __future__ import annotations

import json
import pathlib
import random

OUT = pathlib.Path(__file__).resolve().parent.parent / 'eval' / 'corpus'

# ── Verhoeff ────────────────────────────────────────────────────────────────────
D = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 0, 6, 7, 8, 9, 5],
    [2, 3, 4, 0, 1, 7, 8, 9, 5, 6],
    [3, 4, 0, 1, 2, 8, 9, 5, 6, 7],
    [4, 0, 1, 2, 3, 9, 5, 6, 7, 8],
    [5, 9, 8, 7, 6, 0, 4, 3, 2, 1],
    [6, 5, 9, 8, 7, 1, 0, 4, 3, 2],
    [7, 6, 5, 9, 8, 2, 1, 0, 4, 3],
    [8, 7, 6, 5, 9, 3, 2, 1, 0, 4],
    [9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
]

P = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 5, 7, 6, 2, 8, 3, 0, 9, 4],
    [5, 8, 0, 3, 7, 9, 6, 1, 4, 2],
    [8, 9, 1, 6, 0, 4, 3, 5, 2, 7],
    [9, 4, 5, 3, 1, 2, 6, 8, 7, 0],
    [4, 2, 8, 6, 5, 7, 3, 9, 0, 1],
    [2, 7, 9, 3, 8, 0, 6, 4, 1, 5],
    [7, 0, 4, 6, 9, 1, 3, 2, 5, 8],
]

INV = [0, 4, 3, 2, 1, 5, 6, 7, 8, 9]


def verhoeff_ok(digits: str) -> bool:
    c = 0
    for i, ch in enumerate(reversed(digits)):
        c = D[c][P[i % 8][int(ch)]]
    return c == 0


def verhoeff_check_digit(payload: str) -> int:
    """The digit that makes payload + digit valid."""
    c = 0
    for i, ch in enumerate(reversed(payload)):
        c = D[c][P[(i + 1) % 8][int(ch)]]
    return INV[c]


def make_aadhaar(rng: random.Random) -> str:
    body = str(rng.randint(2, 9)) + ''.join(str(rng.randint(0, 9)) for _ in range(10))
    return body + str(verhoeff_check_digit(body))


# ── Luhn ────────────────────────────────────────────────────────────────────────
def luhn_ok(digits: str) -> bool:
    total = 0
    for i, ch in enumerate(reversed(digits)):
        n = int(ch)
        if i % 2 == 1:
            n *= 2
            if n > 9:
                n -= 9
        total += n
    return total % 10 == 0


def make_card(prefix: str, length: int, rng: random.Random) -> str:
    body = prefix + ''.join(str(rng.randint(0, 9)) for _ in range(length - len(prefix) - 1))
    for d in range(10):
        if luhn_ok(body + str(d)):
            return body + str(d)
    raise AssertionError('unreachable')


# ── PAN and GSTIN ───────────────────────────────────────────────────────────────
ENTITY_TYPES = 'ABCFGHLJPTKE'
B36 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'


def make_pan(rng: random.Random, entity: str = 'P') -> str:
    letters = ''.join(rng.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ') for _ in range(3))
    surname = rng.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    digits = ''.join(str(rng.randint(0, 9)) for _ in range(4))
    check = rng.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    return f'{letters}{entity}{surname}{digits}{check}'


def gstin_check_char(first14: str) -> str:
    total = 0
    for i, ch in enumerate(first14):
        value = B36.index(ch)
        factor = 1 if i % 2 == 0 else 2
        product = value * factor
        total += product // 36 + product % 36
    return B36[(36 - total % 36) % 36]


def make_gstin(rng: random.Random) -> str:
    state = f'{rng.randint(1, 37):02d}'
    pan = make_pan(rng, entity=rng.choice('CP'))
    entity = str(rng.randint(1, 9))
    first14 = f'{state}{pan}{entity}Z'
    return first14 + gstin_check_char(first14)


def main() -> None:
    rng = random.Random(26171)
    OUT.mkdir(parents=True, exist_ok=True)

    valid = []

    for _ in range(8):
        a = make_aadhaar(rng)
        assert verhoeff_ok(a)
        valid.append({'cls': 'AADHAAR', 'text': f'{a[0:4]} {a[4:8]} {a[8:12]}'})
    valid.append({'cls': 'AADHAAR', 'text': make_aadhaar(rng)})
    valid.append({'cls': 'AADHAAR', 'text': '-'.join(
        [(v := make_aadhaar(rng))[0:4], v[4:8], v[8:12]])})

    for entity in 'PCHF':
        valid.append({'cls': 'PAN', 'text': make_pan(rng, entity)})

    for _ in range(3):
        valid.append({'cls': 'GSTIN', 'text': make_gstin(rng)})

    for bank in ('HDFC', 'SBIN', 'ICIC', 'PUNB'):
        branch = ''.join(rng.choice('0123456789') for _ in range(6))
        valid.append({'cls': 'IFSC', 'text': f'{bank}0{branch}'})

    for handle, psp in (('asha.menon', 'okhdfcbank'), ('9845012345', 'paytm'), ('ravi', 'ybl')):
        valid.append({'cls': 'UPI', 'text': f'{handle}@{psp}'})

    for prefix, length in (('4', 16), ('5425', 16), ('34', 15), ('6521', 16)):
        c = make_card(prefix, length, rng)
        assert luhn_ok(c)
        valid.append({'cls': 'CARD', 'text': c})

    for number in ('9845012345', '+91 98450 12345', '08762345678', '7012345678'):
        valid.append({'cls': 'PHONE', 'text': number})

    for address in ('asha.menon@example.in', 'r.kumar+tax@dept.gov.in', 'x@y.co',
                    'name@company.com'):
        valid.append({'cls': 'EMAIL', 'text': address})

    valid.append({'cls': 'PASSPORT', 'text': 'K1234567'})
    valid.append({'cls': 'PASSPORT', 'text': 'M7654321'})
    valid.append({'cls': 'LICENCE', 'text': 'KA0120199912345'})
    valid.append({'cls': 'LICENCE', 'text': 'MH12 20051234567'})

    # Needs a nearby keyword to count; the bare number is not enough.
    valid.append({'cls': 'DOB', 'text': 'DOB: 17/04/1999', 'needsContext': True})
    valid.append({'cls': 'DOB', 'text': 'Date of birth 1999-04-17', 'needsContext': True})
    valid.append({'cls': 'ACCOUNT', 'text': 'Account number 50100234567890', 'needsContext': True})
    valid.append({'cls': 'ACCOUNT', 'text': 'A/c no. 003701548921', 'needsContext': True})

    negatives = [
        # Invoice and order identifiers, including ones that pass Verhoeff by luck.
        {'text': f'Invoice no. {make_aadhaar(rng)}', 'why': 'verhoeff-valid but labelled an invoice'},
        {'text': f'Order ID {make_aadhaar(rng)}', 'why': 'verhoeff-valid but labelled an order'},
        {'text': f'Reference {make_aadhaar(rng)}', 'why': 'verhoeff-valid but labelled a reference'},
        {'text': f'Txn {make_aadhaar(rng)}', 'why': 'verhoeff-valid but labelled a transaction'},
        {'text': 'INV-2024-000123', 'why': 'invoice number'},
        {'text': 'ORD-4532-9981-2210', 'why': 'order id shaped like an Aadhaar'},
        {'text': 'Receipt 2024/00045678', 'why': 'receipt number'},
        {'text': 'Challan 190823456712', 'why': 'twelve digits, fails Verhoeff'},
        {'text': 'Ticket 100000000000', 'why': 'starts with 1, fails the Aadhaar leading rule'},
        {'text': 'Ref 012345678901', 'why': 'starts with 0'},
        # Money.
        {'text': 'Rs. 1,23,456.00', 'why': 'currency amount'},
        {'text': '₹ 45,000', 'why': 'currency amount'},
        {'text': 'Total: 123456.78', 'why': 'decimal amount'},
        {'text': 'INR 9845012345.00', 'why': 'amount that looks like a mobile number'},
        {'text': 'Balance -50100234567890', 'why': 'signed amount'},
        # Dates that are not birthdays.
        {'text': 'Valid until 31/12/2030', 'why': 'expiry date'},
        {'text': 'Issued on 01/04/2024', 'why': 'issue date'},
        {'text': 'Last updated 2024-08-27', 'why': 'timestamp'},
        {'text': 'Meeting on 17/04/2026', 'why': 'future date'},
        {'text': 'Financial year 2023-24', 'why': 'year range'},
        # Names that are also places, and organisations.
        {'text': 'Bangalore', 'why': 'place name'},
        {'text': 'Madras Cafe', 'why': 'place name in a business name'},
        {'text': 'Victoria Terminus', 'why': 'place name'},
        {'text': 'Kerala', 'why': 'state'},
        # Codes that are not identifiers.
        {'text': 'ABCDE1234', 'why': 'nine chars, not a PAN'},
        {'text': 'ABCDE12345', 'why': 'PAN shape but ten chars wrong layout'},
        {'text': 'AAADA0000Z', 'why': 'fourth char D is not a PAN entity type'},
        {'text': 'HDFC1234567', 'why': 'IFSC without the zero in position five'},
        {'text': 'ZZZZ0123456', 'why': 'IFSC shape, unknown bank code'},
        {'text': 'user@localhost', 'why': 'not a UPI PSP'},
        {'text': '4111111111111112', 'why': 'sixteen digits, fails Luhn'},
        {'text': '1234567890123456', 'why': 'sequential digits, fails Luhn'},
        {'text': '0000000000000000', 'why': 'all zeroes'},
        {'text': '5425233430109902', 'why': 'card shape, fails Luhn'},
        # Phone-shaped things that are not phones.
        {'text': '1234567890', 'why': 'ten digits, wrong leading digit'},
        {'text': '5555555555', 'why': 'ten digits, leading 5'},
        {'text': '0000000000', 'why': 'all zeroes'},
        # Version numbers, pincodes in the wrong shape, misc.
        {'text': 'v1.2.3', 'why': 'version'},
        {'text': '192.168.1.1', 'why': 'private IP'},
        {'text': 'Pin 000000', 'why': 'invalid pincode'},
        {'text': 'ISBN 978-3-16-148410-0', 'why': 'ISBN'},
        {'text': 'GSTIN 29ABCDE1234F1Z9', 'why': 'GSTIN shape, wrong check character'},
        {'text': 'PIN 560038', 'why': 'pincode is not high-severity PII on its own'},
        {'text': 'Employee 12345', 'why': 'short id'},
        {'text': 'PO 4500123456', 'why': 'purchase order'},
        {'text': 'Batch 20240827001', 'why': 'batch code'},
        {'text': 'SKU 8901234567890', 'why': 'thirteen digits, fails Luhn'},
        {'text': 'Serial ABCD-EFGH-IJKL', 'why': 'letters only'},
        {'text': 'Case No. 1234/2024', 'why': 'case number'},
        {'text': 'Room 401', 'why': 'small number'},
        {'text': 'Score 98.5%', 'why': 'percentage'},
        {'text': 'Lat 12.9716 Lon 77.5946', 'why': 'coordinates'},
        {'text': 'Temp 36.6 C', 'why': 'measurement'},
        {'text': '+91', 'why': 'country code alone'},
        {'text': 'IFSC', 'why': 'the word, no value'},
        {'text': 'Aadhaar', 'why': 'the word, no value'},
        {'text': 'PAN card', 'why': 'the words, no value'},
        {'text': '2024', 'why': 'a year'},
        {'text': '9,845,012,345', 'why': 'grouped number, not a phone'},
    ]

    payload = {
        'generatedBy': 'scripts/make-pii-fixture.py',
        'seed': 26171,
        'note': (
            'Checksums computed by an independent Python implementation. The TypeScript '
            'validators are tested against these, not against themselves.'
        ),
        'valid': valid,
        'negatives': negatives,
    }

    path = OUT / 'identifiers.json'
    path.write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
    print(f'wrote {path}')
    print(f'  {len(valid)} valid identifiers, {len(negatives)} hard negatives')


if __name__ == '__main__':
    main()
